<?xml version="1.0" encoding="UTF-8"?>
<agentList>
    <changedAgent>
        <id>20677854</id>
        <mu>999999001</mu>
        <acdList>
            <acdStartDate>
                <day>13</day>
                <month>12</month>
                <year>2019</year>
            </acdStartDate>
            <acd>
                <acdID>103</acdID>
                <logon></logon>
            </acd>
        </acdList>
        <forceWork>N</forceWork>
        <tourGroup></tourGroup>
        <availListDateRange>
            <day>13</day>
            <month>12</month>
            <year>2019</year>
            <weeks>29</weeks>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
        <skillSet>
            <skillStartDate>
                <day>13</day>
                <month>12</month>
                <year>2019</year>
            </skillStartDate>
            <baseScheduleCode>* TERMINATION</baseScheduleCode>
            <skill>
                <skillName>TERM</skillName>
                <level>1</level>
            </skill>
        </skillSet>
        <agentData>
            <group>
                <description>_SYSTEM MESSAGE</description>
                <adgStartDate>
                    <day>17</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>AGENT TERMED BY AATP</value>
            </group>
            <group>
                <description>_SUPERVISOR</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>TERM</value>
            </group>
            <group>
                <description>_EMPLOYMENT END DATE</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>20191213</value>
            </group>
        </agentData>
    </changedAgent>
    <changedAgent>
        <id>20836636</id>
        <mu>999999001</mu>
        <acdList>
            <acdStartDate>
                <day>11</day>
                <month>12</month>
                <year>2019</year>
            </acdStartDate>
            <acd>
                <acdID>103</acdID>
                <logon></logon>
            </acd>
        </acdList>
        <forceWork>N</forceWork>
        <tourGroup></tourGroup>
        <availListDateRange>
            <day>11</day>
            <month>12</month>
            <year>2019</year>
            <weeks>29</weeks>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
        <skillSet>
            <skillStartDate>
                <day>11</day>
                <month>12</month>
                <year>2019</year>
            </skillStartDate>
            <baseScheduleCode>* TERMINATION</baseScheduleCode>
            <skill>
                <skillName>TERM</skillName>
                <level>1</level>
            </skill>
        </skillSet>
        <agentData>
            <group>
                <description>_SYSTEM MESSAGE</description>
                <adgStartDate>
                    <day>17</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>AGENT TERMED BY AATP</value>
            </group>
            <group>
                <description>_SUPERVISOR</description>
                <adgStartDate>
                    <day>11</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>TERM</value>
            </group>
            <group>
                <description>_EMPLOYMENT END DATE</description>
                <adgStartDate>
                    <day>11</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>20191211</value>
            </group>
        </agentData>
    </changedAgent>
    <changedAgent>
        <id>20812817</id>
        <mu>999999001</mu>
        <forceWork>N</forceWork>
        <tourGroup></tourGroup>
        <availListDateRange>
            <day>13</day>
            <month>12</month>
            <year>2019</year>
            <weeks>29</weeks>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
        <skillSet>
            <skillStartDate>
                <day>13</day>
                <month>12</month>
                <year>2019</year>
            </skillStartDate>
            <baseScheduleCode>* TERMINATION</baseScheduleCode>
            <skill>
                <skillName>TERM</skillName>
                <level>1</level>
            </skill>
        </skillSet>
        <agentData>
            <group>
                <description>_SYSTEM MESSAGE</description>
                <adgStartDate>
                    <day>17</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>AGENT TERMED BY AATP</value>
            </group>
            <group>
                <description>_SUPERVISOR</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>TERM</value>
            </group>
            <group>
                <description>_EMPLOYMENT END DATE</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>20191213</value>
            </group>
        </agentData>
    </changedAgent>
    <changedAgent>
        <id>20812817</id>
        <mu>999999001</mu>
        <forceWork>N</forceWork>
        <tourGroup></tourGroup>
        <availListDateRange>
            <day>13</day>
            <month>12</month>
            <year>2019</year>
            <weeks>29</weeks>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
        <skillSet>
            <skillStartDate>
                <day>13</day>
                <month>12</month>
                <year>2019</year>
            </skillStartDate>
            <baseScheduleCode>* TERMINATION</baseScheduleCode>
            <skill>
                <skillName>TERM</skillName>
                <level>1</level>
            </skill>
        </skillSet>
        <agentData>
            <group>
                <description>_SYSTEM MESSAGE</description>
                <adgStartDate>
                    <day>17</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>AGENT TERMED BY AATP</value>
            </group>
            <group>
                <description>_SUPERVISOR</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>TERM</value>
            </group>
            <group>
                <description>_EMPLOYMENT END DATE</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>20191213</value>
            </group>
        </agentData>
    </changedAgent>
    <changedAgent>
        <id>52142663</id>
        <mu>999999001</mu>
        <forceWork>N</forceWork>
        <tourGroup></tourGroup>
        <availListDateRange>
            <day>11</day>
            <month>12</month>
            <year>2019</year>
            <weeks>29</weeks>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
        <skillSet>
            <skillStartDate>
                <day>11</day>
                <month>12</month>
                <year>2019</year>
            </skillStartDate>
            <baseScheduleCode>* TERMINATION</baseScheduleCode>
            <skill>
                <skillName>TERM</skillName>
                <level>1</level>
            </skill>
        </skillSet>
        <agentData>
            <group>
                <description>_SYSTEM MESSAGE</description>
                <adgStartDate>
                    <day>17</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>AGENT TERMED BY AATP</value>
            </group>
            <group>
                <description>_SUPERVISOR</description>
                <adgStartDate>
                    <day>11</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>TERM</value>
            </group>
            <group>
                <description>_EMPLOYMENT END DATE</description>
                <adgStartDate>
                    <day>11</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>20191211</value>
            </group>
        </agentData>
    </changedAgent>
    <changedAgent>
        <id>52166839</id>
        <mu>999999001</mu>
        <forceWork>N</forceWork>
        <tourGroup></tourGroup>
        <availListDateRange>
            <day>13</day>
            <month>12</month>
            <year>2019</year>
            <weeks>29</weeks>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
        <skillSet>
            <skillStartDate>
                <day>13</day>
                <month>12</month>
                <year>2019</year>
            </skillStartDate>
            <baseScheduleCode>* TERMINATION</baseScheduleCode>
            <skill>
                <skillName>TERM</skillName>
                <level>1</level>
            </skill>
        </skillSet>
        <agentData>
            <group>
                <description>_SYSTEM MESSAGE</description>
                <adgStartDate>
                    <day>17</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>AGENT TERMED BY AATP</value>
            </group>
            <group>
                <description>_SUPERVISOR</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>TERM</value>
            </group>
            <group>
                <description>_EMPLOYMENT END DATE</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>20191213</value>
            </group>
        </agentData>
    </changedAgent>
    <changedAgent>
        <id>52175641</id>
        <mu>999999001</mu>
        <forceWork>N</forceWork>
        <tourGroup></tourGroup>
        <availListDateRange>
            <day>11</day>
            <month>12</month>
            <year>2019</year>
            <weeks>29</weeks>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
        <skillSet>
            <skillStartDate>
                <day>11</day>
                <month>12</month>
                <year>2019</year>
            </skillStartDate>
            <baseScheduleCode>* TERMINATION</baseScheduleCode>
            <skill>
                <skillName>TERM</skillName>
                <level>1</level>
            </skill>
        </skillSet>
        <agentData>
            <group>
                <description>_SYSTEM MESSAGE</description>
                <adgStartDate>
                    <day>17</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>AGENT TERMED BY AATP</value>
            </group>
            <group>
                <description>_SUPERVISOR</description>
                <adgStartDate>
                    <day>11</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>TERM</value>
            </group>
            <group>
                <description>_EMPLOYMENT END DATE</description>
                <adgStartDate>
                    <day>11</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>20191211</value>
            </group>
        </agentData>
    </changedAgent>
    <changedAgent>
        <id>20829660</id>
        <mu>999999001</mu>
        <acdList>
            <acdStartDate>
                <day>13</day>
                <month>12</month>
                <year>2019</year>
            </acdStartDate>
            <acd>
                <acdID>109</acdID>
                <logon></logon>
            </acd>
        </acdList>
        <forceWork>N</forceWork>
        <tourGroup></tourGroup>
        <availListDateRange>
            <day>13</day>
            <month>12</month>
            <year>2019</year>
            <weeks>29</weeks>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
        <skillSet>
            <skillStartDate>
                <day>13</day>
                <month>12</month>
                <year>2019</year>
            </skillStartDate>
            <baseScheduleCode>* TERMINATION</baseScheduleCode>
            <skill>
                <skillName>TERM</skillName>
                <level>1</level>
            </skill>
        </skillSet>
        <agentData>
            <group>
                <description>_SYSTEM MESSAGE</description>
                <adgStartDate>
                    <day>17</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>AGENT TERMED BY AATP</value>
            </group>
            <group>
                <description>_SUPERVISOR</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>TERM</value>
            </group>
            <group>
                <description>_EMPLOYMENT END DATE</description>
                <adgStartDate>
                    <day>13</day>
                    <month>12</month>
                    <year>2019</year>
                </adgStartDate>
                <value>20191213</value>
            </group>
        </agentData>
    </changedAgent>
    <changedAgent>
        <id>20677854</id>
        <availListDateRange>
            <default></default>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
    </changedAgent>
    <changedAgent>
        <id>20836636</id>
        <availListDateRange>
            <default></default>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
    </changedAgent>
    <changedAgent>
        <id>20812817</id>
        <availListDateRange>
            <default></default>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
    </changedAgent>
    <changedAgent>
        <id>20812817</id>
        <availListDateRange>
            <default></default>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
    </changedAgent>
    <changedAgent>
        <id>52142663</id>
        <availListDateRange>
            <default></default>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
    </changedAgent>
    <changedAgent>
        <id>52166839</id>
        <availListDateRange>
            <default></default>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
    </changedAgent>
    <changedAgent>
        <id>52175641</id>
        <availListDateRange>
            <default></default>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
    </changedAgent>
    <changedAgent>
        <id>20829660</id>
        <availListDateRange>
            <default></default>
        </availListDateRange>
        <availabilityList>
            <availability day="All">NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNN</availability>
        </availabilityList>
    </changedAgent>
</agentList>